name: Prometheus CI check

on:
  push:
    branches: [ master ]
    paths:
      - monitoring/prometheus/**
  pull_request:
    branches: [ master ]
    paths:
      - monitoring/prometheus/**

jobs:

  test-prometheus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --no-cache -f monitoring/prometheus/tests/Dockerfile -t prometheus-test monitoring/prometheus
